#!perl

use v5.40;
use experimental qw[ class ];

# these are the units generated by the assembler
# and fed into the CPU

class VM::Instructions::Opcode {
    use overload '""' => \&to_string;

    field $instruction :param :reader;
    field $operand1    :param :reader = undef;
    field $operand2    :param :reader = undef;

    method to_string {
        sprintf 'Op[%s](%s)',
            $instruction,
            join ', ' => ($operand1 // ()), ($operand2 // ())
    }
}
